name: Test Coverage Enforcement

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  coverage-check:
    name: Verify 100% Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Tests with JaCoCo
        run: |
          chmod +x ./gradlew
          ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification
          ./gradlew jacocoTestCoverageVerification

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if tests fail
        with:
          name: jacoco-coverage-report
          path: |
            build/reports/jacoco/test/html/
            build/reports/jacoco/test.xml
